### PR TITLE
Add copy assignment operator

### PR DESCRIPTION
**Pull request by MartinMoizard**

### CODE REVIEW

**Comment by pahowes** [comment]
None of the existing tests call this method. All of the test_any_construct_special_\* tests invoke any(any&) even when any(any const&) exists. Can you provide a test case that would trigger the copy constructor?

**Comment by MartinMoizard** [comment]
Done :)

**Comment by pahowes** [comment]
Awesome! Thanks! I rearranged things a bit and added tests for the other assignment operators. Pull from master and see if everything works for you now.

**Comment by MartinMoizard** [comment]
Actually I am not sure why you want to delete the _value of the type::any being copied (in all operator= functions)

For instance, with the current code:
type::any a(true);
type::any b;
b = a;
--> here a is not valid anymore, is it really expected?

**Comment by MartinMoizard** [comment]
Sounds good to me. My pull request had indeed a leak that you fixed. Thanks for that

**Comment by pahowes** [comment]
You asked a question in this discussion thread that came through my email, but doesn't show up here: Why do I delete `_value` in `type::any` in all of the `operator=` methods?

The answer is simple: reassignment. For example:

``` c++
type::any a;
a = true;
a = 1;
a = "string";
```

In each case, the underlying pointer must be deleted, otherwise a memory leak occurs.

**Comment by MartinMoizard** [comment]
I asked a question but then I deleted it after reading the code again. Thanks for your help :)

**Pull request closed without merging**
